import type { Metadata } from "next";
import { Geist, Poppins, Open_Sans, Fjalla_One } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";


const primary = Poppins({ 
  variable: "--font-primary",
  subsets: ["latin"], 
  weight: ["400", "700"],
  display: "swap",
});

const secundary = Geist({
  variable: "--font-secundary",
  subsets: ["latin"],
  weight: ["800"],
  display: "swap",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let theme: string= 'dark'

  return (
    <html lang="es">
      <body
        className={`${primary.variable} ${secundary.variable} antialiased overflow-x-hidden w-full`}
      >
        <Navbar theme={theme}/>
        {children}
      </body>
    </html>
  );
}
